# This is a basic workflow to help you get started with Actions

name: UPDATE-INDEX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        persist-credentials: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Run extract_data.py
      run: |
        pwd
        git pull
        cd src/data/ && python3 extract_data.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status | grep "nothing to commit" && echo "Nothing to commit." || git commit -m "Auto-update index" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  deploy: 
    runs-on: ubuntu-22.04 
    needs: [build]
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v3.4.1
    - name: Setup SSH auth
      env:
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_AGENT_PRIVATE_KEY}}
        SSH_PUBLIC_KEY: ${{secrets.DEPLOY_AGENT_PUBLIC_KEY}}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
        chmod 700 ~/.ssh/id_rsa.pub
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        echo SSH agent started
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ssh-key: ${{secrets.DEPLOY_AGENT_PRIVATE_KEY}}
        fetch-depth: 0
        ref: master
      #uses: actions/checkout@master 
      #with:
      #  persist-credentials: false 
      #  fetch-depth: 0
    - name: Config Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Install npm dependencies
      run: npm install
    - name: Deploy
      run: npm run deploy
